refactor(pre-commit): use git clang-format

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,26 +1,10 @@
 #!/bin/bash
 
-# Liste des répertoires à exclure
-exclude_dirs=("libs/deps" "build")
+clangformatout=$(git clang-format --diff --staged -q)
 
-# Récupérer la liste des fichiers à valider
-files_to_format=$(git diff --cached --name-only | grep -E '\.cpp$|\.hpp$')
-
-# Formater les fichiers
-for file in $files_to_format; do
-    exclude=false
-
-    # Vérifie si le fichier se trouve dans un répertoire exclu
-    for dir in "${exclude_dirs[@]}"; do
-        if [[ "$file" == *"$dir"* ]]; then
-            exclude=true
-            break
-        fi
-    done
-
-    # Si le fichier n'est pas exclu, existe sur le système de fichiers et n'est pas un dossier, exécute clang-format
-    if [ "$exclude" = false ] && [ -e "$file" ]; then
-        clang-format -i "$file"
-        echo "Formatted $file"
-    fi
-done
+if [ "$clangformatout" != "" ]
+then
+    echo "Format error!"
+    git clang-format
+    exit 1
+fi
